/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackendMetadata { 'version' : Version, 'environment' : Env }
export type Env = { 'dev' : null } |
  { 'prod' : null };
export type Money = bigint;
export type Name = string;
export interface Product {
  'id' : ProductId,
  'title' : string,
  'isPublished' : boolean,
  'ownerPrincipal' : Principal,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'imageUrl' : string,
  'currency' : ProductCurrency,
  'category' : string,
  'price' : Money,
}
export type ProductCurrency = string;
export type ProductId = bigint;
export type Timestamp = bigint;
export interface UpgradeSummary {
  'lastProductId' : bigint,
  'productCount' : bigint,
  'version' : bigint,
  'vendorCount' : bigint,
  'lastVendorId' : bigint,
}
export type Url = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VendorId = bigint;
export interface VendorProfile {
  'id' : VendorId,
  'user' : Principal,
  'logoUrl' : Url,
  'isVerified' : boolean,
  'companyName' : Name,
}
export type Version = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVendorProfile' : ActorMethod<[VendorProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, string, bigint, string, string, string, boolean],
    ProductId
  >,
  'createVendorProfile' : ActorMethod<[string, string], VendorId>,
  'getAllVendorProfiles' : ActorMethod<[], Array<VendorProfile>>,
  'getBackendMetadata' : ActorMethod<[], BackendMetadata>,
  'getCallerProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerVendorProfile' : ActorMethod<[], [] | [VendorProfile]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getPublishedProducts' : ActorMethod<[], Array<Product>>,
  'getTotalVendorCount' : ActorMethod<[], bigint>,
  'getUpgradeSummary' : ActorMethod<[], UpgradeSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendorProductsByPrincipal' : ActorMethod<[Principal], Array<Product>>,
  'getVendorProductsByVendorId' : ActorMethod<[VendorId], Array<Product>>,
  'getVendorProfile' : ActorMethod<[VendorId], [] | [VendorProfile]>,
  'getVendorProfileByUser' : ActorMethod<[Principal], [] | [VendorProfile]>,
  'getVerifiedVendorProfiles' : ActorMethod<[], Array<VendorProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPublishedProductsByVendor' : ActorMethod<[Principal], Array<Product>>,
  'listVerifiedVendors' : ActorMethod<[], Array<VendorProfile>>,
  'ping' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, bigint, string, string, string, boolean],
    undefined
  >,
  'updateVendorProfile' : ActorMethod<[VendorId, string, string], undefined>,
  'upsertCallerVendorProfile' : ActorMethod<[string, string], VendorId>,
  'verifyVendor' : ActorMethod<[VendorId], undefined>,
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];