/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackendMetadata { 'version' : Version, 'environment' : Env }
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type Env = { 'dev' : null } |
  { 'prod' : null };
export type Money = bigint;
export type Name = string;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : Money,
  'currency' : string,
  'buyer' : Principal,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'title' : string,
  'productId' : ProductId,
  'currency' : string,
  'quantity' : bigint,
  'price' : Money,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Organization {
  'id' : OrganizationId,
  'adminPrincipal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'logoUrl' : string,
  'vendorIds' : Array<VendorId>,
}
export type OrganizationId = bigint;
export interface Product {
  'id' : ProductId,
  'title' : string,
  'isPublished' : boolean,
  'ownerPrincipal' : Principal,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'imageUrl' : string,
  'currency' : ProductCurrency,
  'category' : string,
  'price' : Money,
}
export type ProductCurrency = string;
export type ProductId = bigint;
export type Timestamp = bigint;
export interface UpgradeSummary {
  'lastProductId' : bigint,
  'productCount' : bigint,
  'version' : bigint,
  'vendorCount' : bigint,
  'lastVendorId' : bigint,
}
export type Url = string;
export interface UserProfile { 'name' : string }
export interface UserProfileWithPrincipal {
  'principal' : Principal,
  'profile' : UserProfile,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VendorId = bigint;
export interface VendorProfile {
  'id' : VendorId,
  'user' : Principal,
  'logoUrl' : Url,
  'isVerified' : boolean,
  'companyName' : Name,
}
export type Version = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'addVendorProfile' : ActorMethod<[VendorProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignVendorToOrg' : ActorMethod<[OrganizationId, VendorId], undefined>,
  'bootstrapAdmins' : ActorMethod<[Array<Principal>], undefined>,
  'bootstrapFirstAdmin' : ActorMethod<[], undefined>,
  'claimAppOwner' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrganization' : ActorMethod<[string, string, string], OrganizationId>,
  'createProduct' : ActorMethod<
    [string, string, bigint, string, string, string, boolean],
    ProductId
  >,
  'createVendorProfile' : ActorMethod<[string, string], VendorId>,
  'deleteOrganization' : ActorMethod<[OrganizationId], undefined>,
  'getAdmins' : ActorMethod<[], Array<Principal>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllOrganizations' : ActorMethod<[], Array<Organization>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileWithPrincipal>>,
  'getAllVendorProfiles' : ActorMethod<[], Array<VendorProfile>>,
  'getAppOwner' : ActorMethod<[], [] | [Principal]>,
  'getBackendMetadata' : ActorMethod<[], BackendMetadata>,
  'getCallerOrders' : ActorMethod<[], Array<Order>>,
  'getCallerProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerVendorProfile' : ActorMethod<[], [] | [VendorProfile]>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrganization' : ActorMethod<[OrganizationId], [] | [Organization]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getPublishedProducts' : ActorMethod<[], Array<Product>>,
  'getTotalOrderCount' : ActorMethod<[], bigint>,
  'getTotalUserCount' : ActorMethod<[], bigint>,
  'getTotalVendorCount' : ActorMethod<[], bigint>,
  'getUpgradeSummary' : ActorMethod<[], UpgradeSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendorOrders' : ActorMethod<[], Array<Order>>,
  'getVendorOrganization' : ActorMethod<[VendorId], [] | [Organization]>,
  'getVendorProductsByPrincipal' : ActorMethod<[Principal], Array<Product>>,
  'getVendorProductsByVendorId' : ActorMethod<[VendorId], Array<Product>>,
  'getVendorProfile' : ActorMethod<[VendorId], [] | [VendorProfile]>,
  'getVendorProfileByUser' : ActorMethod<[Principal], [] | [VendorProfile]>,
  'getVerifiedVendorProfiles' : ActorMethod<[], Array<VendorProfile>>,
  'hasAdmin' : ActorMethod<[], boolean>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isAdminInternal' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerAppOwner' : ActorMethod<[], boolean>,
  'listPublishedProductsByVendor' : ActorMethod<[Principal], Array<Product>>,
  'listVerifiedVendors' : ActorMethod<[], Array<VendorProfile>>,
  'ping' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], OrderId>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeVendorFromOrg' : ActorMethod<[OrganizationId, VendorId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdmins' : ActorMethod<[Array<Principal>], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, bigint, string, string, string, boolean],
    undefined
  >,
  'updateVendorProfile' : ActorMethod<[VendorId, string, string], undefined>,
  'upsertCallerVendorProfile' : ActorMethod<[string, string], VendorId>,
  'verifyVendor' : ActorMethod<[VendorId], undefined>,
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];