/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const VendorId = IDL.Nat;
export const Url = IDL.Text;
export const Name = IDL.Text;
export const VendorProfile = IDL.Record({
  'id' : VendorId,
  'user' : IDL.Principal,
  'logoUrl' : Url,
  'isVerified' : IDL.Bool,
  'companyName' : Name,
});
export const OrganizationId = IDL.Nat;
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Money = IDL.Nat;
export const OrderItem = IDL.Record({
  'title' : IDL.Text,
  'productId' : ProductId,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : Money,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : Money,
  'currency' : IDL.Text,
  'buyer' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
});
export const Organization = IDL.Record({
  'id' : OrganizationId,
  'adminPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
  'vendorIds' : IDL.Vec(VendorId),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserProfileWithPrincipal = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : UserProfile,
});
export const Version = IDL.Text;
export const Env = IDL.Variant({ 'dev' : IDL.Null, 'prod' : IDL.Null });
export const BackendMetadata = IDL.Record({
  'version' : Version,
  'environment' : Env,
});
export const ProductCurrency = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'ownerPrincipal' : IDL.Principal,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'imageUrl' : IDL.Text,
  'currency' : ProductCurrency,
  'category' : IDL.Text,
  'price' : Money,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const UpgradeSummary = IDL.Record({
  'lastProductId' : IDL.Nat,
  'productCount' : IDL.Nat,
  'version' : IDL.Nat,
  'vendorCount' : IDL.Nat,
  'lastVendorId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'addVendorProfile' : IDL.Func([VendorProfile], [], []),
  'assignVendorToOrg' : IDL.Func([OrganizationId, VendorId], [], []),
  'bootstrapAdmins' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
  'bootstrapFirstAdmin' : IDL.Func([], [], []),
  'claimAppOwner' : IDL.Func([], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createOrganization' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [OrganizationId],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [ProductId],
      [],
    ),
  'createVendorProfile' : IDL.Func([IDL.Text, IDL.Text], [VendorId], []),
  'deleteOrganization' : IDL.Func([OrganizationId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllOrganizations' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(UserProfileWithPrincipal)],
      ['query'],
    ),
  'getAllVendorProfiles' : IDL.Func([], [IDL.Vec(VendorProfile)], ['query']),
  'getAppOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getBackendMetadata' : IDL.Func([], [BackendMetadata], ['query']),
  'getCallerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerVendorProfile' : IDL.Func([], [IDL.Opt(VendorProfile)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrganization' : IDL.Func(
      [OrganizationId],
      [IDL.Opt(Organization)],
      ['query'],
    ),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getPublishedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getTotalOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalVendorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUpgradeSummary' : IDL.Func([], [UpgradeSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendorOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getVendorOrganization' : IDL.Func(
      [VendorId],
      [IDL.Opt(Organization)],
      ['query'],
    ),
  'getVendorProductsByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getVendorProductsByVendorId' : IDL.Func(
      [VendorId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getVendorProfile' : IDL.Func(
      [VendorId],
      [IDL.Opt(VendorProfile)],
      ['query'],
    ),
  'getVendorProfileByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(VendorProfile)],
      ['query'],
    ),
  'getVerifiedVendorProfiles' : IDL.Func(
      [],
      [IDL.Vec(VendorProfile)],
      ['query'],
    ),
  'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isAdminInternal' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAppOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'isVendorSuspended' : IDL.Func([VendorId], [IDL.Bool], ['query']),
  'listPublishedProductsByVendor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'listVerifiedVendors' : IDL.Func([], [IDL.Vec(VendorProfile)], ['query']),
  'ping' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [OrderId], []),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'removeVendorFromOrg' : IDL.Func([OrganizationId, VendorId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdmins' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
  'suspendVendor' : IDL.Func([VendorId], [], []),
  'unsuspendVendor' : IDL.Func([VendorId], [], []),
  'unverifyVendor' : IDL.Func([VendorId], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateOrganization' : IDL.Func(
      [OrganizationId, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateVendorProfile' : IDL.Func([VendorId, IDL.Text, IDL.Text], [], []),
  'upsertCallerVendorProfile' : IDL.Func([IDL.Text, IDL.Text], [VendorId], []),
  'verifyVendor' : IDL.Func([VendorId], [], []),
  'whoami' : IDL.Func([], [IDL.Principal], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const VendorId = IDL.Nat;
  const Url = IDL.Text;
  const Name = IDL.Text;
  const VendorProfile = IDL.Record({
    'id' : VendorId,
    'user' : IDL.Principal,
    'logoUrl' : Url,
    'isVerified' : IDL.Bool,
    'companyName' : Name,
  });
  const OrganizationId = IDL.Nat;
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Money = IDL.Nat;
  const OrderItem = IDL.Record({
    'title' : IDL.Text,
    'productId' : ProductId,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : Money,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'totalAmount' : Money,
    'currency' : IDL.Text,
    'buyer' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
  });
  const Organization = IDL.Record({
    'id' : OrganizationId,
    'adminPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
    'vendorIds' : IDL.Vec(VendorId),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserProfileWithPrincipal = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : UserProfile,
  });
  const Version = IDL.Text;
  const Env = IDL.Variant({ 'dev' : IDL.Null, 'prod' : IDL.Null });
  const BackendMetadata = IDL.Record({
    'version' : Version,
    'environment' : Env,
  });
  const ProductCurrency = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'ownerPrincipal' : IDL.Principal,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'imageUrl' : IDL.Text,
    'currency' : ProductCurrency,
    'category' : IDL.Text,
    'price' : Money,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const UpgradeSummary = IDL.Record({
    'lastProductId' : IDL.Nat,
    'productCount' : IDL.Nat,
    'version' : IDL.Nat,
    'vendorCount' : IDL.Nat,
    'lastVendorId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'addVendorProfile' : IDL.Func([VendorProfile], [], []),
    'assignVendorToOrg' : IDL.Func([OrganizationId, VendorId], [], []),
    'bootstrapAdmins' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
    'bootstrapFirstAdmin' : IDL.Func([], [], []),
    'claimAppOwner' : IDL.Func([], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createOrganization' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [OrganizationId],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [ProductId],
        [],
      ),
    'createVendorProfile' : IDL.Func([IDL.Text, IDL.Text], [VendorId], []),
    'deleteOrganization' : IDL.Func([OrganizationId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllOrganizations' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(UserProfileWithPrincipal)],
        ['query'],
      ),
    'getAllVendorProfiles' : IDL.Func([], [IDL.Vec(VendorProfile)], ['query']),
    'getAppOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getBackendMetadata' : IDL.Func([], [BackendMetadata], ['query']),
    'getCallerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerVendorProfile' : IDL.Func(
        [],
        [IDL.Opt(VendorProfile)],
        ['query'],
      ),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrganization' : IDL.Func(
        [OrganizationId],
        [IDL.Opt(Organization)],
        ['query'],
      ),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getPublishedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getTotalOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalVendorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUpgradeSummary' : IDL.Func([], [UpgradeSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendorOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getVendorOrganization' : IDL.Func(
        [VendorId],
        [IDL.Opt(Organization)],
        ['query'],
      ),
    'getVendorProductsByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getVendorProductsByVendorId' : IDL.Func(
        [VendorId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getVendorProfile' : IDL.Func(
        [VendorId],
        [IDL.Opt(VendorProfile)],
        ['query'],
      ),
    'getVendorProfileByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(VendorProfile)],
        ['query'],
      ),
    'getVerifiedVendorProfiles' : IDL.Func(
        [],
        [IDL.Vec(VendorProfile)],
        ['query'],
      ),
    'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isAdminInternal' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAppOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'isVendorSuspended' : IDL.Func([VendorId], [IDL.Bool], ['query']),
    'listPublishedProductsByVendor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listVerifiedVendors' : IDL.Func([], [IDL.Vec(VendorProfile)], ['query']),
    'ping' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [OrderId], []),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'removeVendorFromOrg' : IDL.Func([OrganizationId, VendorId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdmins' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
    'suspendVendor' : IDL.Func([VendorId], [], []),
    'unsuspendVendor' : IDL.Func([VendorId], [], []),
    'unverifyVendor' : IDL.Func([VendorId], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateOrganization' : IDL.Func(
        [OrganizationId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateVendorProfile' : IDL.Func([VendorId, IDL.Text, IDL.Text], [], []),
    'upsertCallerVendorProfile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [VendorId],
        [],
      ),
    'verifyVendor' : IDL.Func([VendorId], [], []),
    'whoami' : IDL.Func([], [IDL.Principal], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };