/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VendorId = IDL.Nat;
export const Url = IDL.Text;
export const Name = IDL.Text;
export const VendorProfile = IDL.Record({
  'id' : VendorId,
  'user' : IDL.Principal,
  'logoUrl' : Url,
  'isVerified' : IDL.Bool,
  'companyName' : Name,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const Version = IDL.Text;
export const Env = IDL.Variant({ 'dev' : IDL.Null, 'prod' : IDL.Null });
export const BackendMetadata = IDL.Record({
  'version' : Version,
  'environment' : Env,
});
export const Timestamp = IDL.Int;
export const ProductCurrency = IDL.Text;
export const Money = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'ownerPrincipal' : IDL.Principal,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'imageUrl' : IDL.Text,
  'currency' : ProductCurrency,
  'category' : IDL.Text,
  'price' : Money,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UpgradeSummary = IDL.Record({
  'lastProductId' : IDL.Nat,
  'productCount' : IDL.Nat,
  'version' : IDL.Nat,
  'vendorCount' : IDL.Nat,
  'lastVendorId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addVendorProfile' : IDL.Func([VendorProfile], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapAdmins' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
  'bootstrapFirstAdmin' : IDL.Func([], [], []),
  'claimAppOwner' : IDL.Func([], [], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [ProductId],
      [],
    ),
  'createVendorProfile' : IDL.Func([IDL.Text, IDL.Text], [VendorId], []),
  'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllVendorProfiles' : IDL.Func([], [IDL.Vec(VendorProfile)], ['query']),
  'getAppOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getBackendMetadata' : IDL.Func([], [BackendMetadata], ['query']),
  'getCallerProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerVendorProfile' : IDL.Func([], [IDL.Opt(VendorProfile)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getPublishedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getTotalVendorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUpgradeSummary' : IDL.Func([], [UpgradeSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendorProductsByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getVendorProductsByVendorId' : IDL.Func(
      [VendorId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getVendorProfile' : IDL.Func(
      [VendorId],
      [IDL.Opt(VendorProfile)],
      ['query'],
    ),
  'getVendorProfileByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(VendorProfile)],
      ['query'],
    ),
  'getVerifiedVendorProfiles' : IDL.Func(
      [],
      [IDL.Vec(VendorProfile)],
      ['query'],
    ),
  'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isAdminInternal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAppOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'listPublishedProductsByVendor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'listVerifiedVendors' : IDL.Func([], [IDL.Vec(VendorProfile)], ['query']),
  'ping' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdmins' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateVendorProfile' : IDL.Func([VendorId, IDL.Text, IDL.Text], [], []),
  'upsertCallerVendorProfile' : IDL.Func([IDL.Text, IDL.Text], [VendorId], []),
  'verifyVendor' : IDL.Func([VendorId], [], []),
  'whoami' : IDL.Func([], [IDL.Principal], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VendorId = IDL.Nat;
  const Url = IDL.Text;
  const Name = IDL.Text;
  const VendorProfile = IDL.Record({
    'id' : VendorId,
    'user' : IDL.Principal,
    'logoUrl' : Url,
    'isVerified' : IDL.Bool,
    'companyName' : Name,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const Version = IDL.Text;
  const Env = IDL.Variant({ 'dev' : IDL.Null, 'prod' : IDL.Null });
  const BackendMetadata = IDL.Record({
    'version' : Version,
    'environment' : Env,
  });
  const Timestamp = IDL.Int;
  const ProductCurrency = IDL.Text;
  const Money = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'ownerPrincipal' : IDL.Principal,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'imageUrl' : IDL.Text,
    'currency' : ProductCurrency,
    'category' : IDL.Text,
    'price' : Money,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UpgradeSummary = IDL.Record({
    'lastProductId' : IDL.Nat,
    'productCount' : IDL.Nat,
    'version' : IDL.Nat,
    'vendorCount' : IDL.Nat,
    'lastVendorId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addVendorProfile' : IDL.Func([VendorProfile], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapAdmins' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
    'bootstrapFirstAdmin' : IDL.Func([], [], []),
    'claimAppOwner' : IDL.Func([], [], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [ProductId],
        [],
      ),
    'createVendorProfile' : IDL.Func([IDL.Text, IDL.Text], [VendorId], []),
    'getAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllVendorProfiles' : IDL.Func([], [IDL.Vec(VendorProfile)], ['query']),
    'getAppOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getBackendMetadata' : IDL.Func([], [BackendMetadata], ['query']),
    'getCallerProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerVendorProfile' : IDL.Func(
        [],
        [IDL.Opt(VendorProfile)],
        ['query'],
      ),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getPublishedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getTotalVendorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUpgradeSummary' : IDL.Func([], [UpgradeSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendorProductsByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getVendorProductsByVendorId' : IDL.Func(
        [VendorId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getVendorProfile' : IDL.Func(
        [VendorId],
        [IDL.Opt(VendorProfile)],
        ['query'],
      ),
    'getVendorProfileByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(VendorProfile)],
        ['query'],
      ),
    'getVerifiedVendorProfiles' : IDL.Func(
        [],
        [IDL.Vec(VendorProfile)],
        ['query'],
      ),
    'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isAdminInternal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAppOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'listPublishedProductsByVendor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listVerifiedVendors' : IDL.Func([], [IDL.Vec(VendorProfile)], ['query']),
    'ping' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdmins' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateVendorProfile' : IDL.Func([VendorId, IDL.Text, IDL.Text], [], []),
    'upsertCallerVendorProfile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [VendorId],
        [],
      ),
    'verifyVendor' : IDL.Func([VendorId], [], []),
    'whoami' : IDL.Func([], [IDL.Principal], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };